"""added resume field

Revision ID: 085f4c565a6c
Revises: 05bbc5964aab
Create Date: 2025-10-09 20:00:39.087014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085f4c565a6c'
down_revision: Union[str, Sequence[str], None] = '05bbc5964aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_interview_attempts', sa.Column('resume', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_interview_attempts', 'resume')
    # ### end Alembic commands ###
