"""delete row

Revision ID: 2257a6814a3e
Revises: 9f083ec0a8c0
Create Date: 2025-10-20 18:27:16.623936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2257a6814a3e'
down_revision: Union[str, Sequence[str], None] = '9f083ec0a8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_interviews', 'questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_interviews', sa.Column('questions', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
