"""changes in publicinterview attempt table

Revision ID: 69512801f1a1
Revises: 2257a6814a3e
Create Date: 2025-10-20 19:22:05.658969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '69512801f1a1'
down_revision: Union[str, Sequence[str], None] = '2257a6814a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_interview_attempts', sa.Column('transcript', sa.JSON(), nullable=True))
    op.drop_column('public_interview_attempts', 'answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_interview_attempts', sa.Column('answers', sqlite.JSON(), nullable=True))
    op.drop_column('public_interview_attempts', 'transcript')
    # ### end Alembic commands ###
