"""add interview_time field in APPLICANT table

Revision ID: 8b69ef4c92ad
Revises: 958d8a967fc0
Create Date: 2025-10-14 18:20:05.268152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b69ef4c92ad'
down_revision: Union[str, Sequence[str], None] = '958d8a967fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('interview_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'interview_time')
    # ### end Alembic commands ###
