"""add email field in APPLICANT table

Revision ID: 958d8a967fc0
Revises: fbde3b86fceb
Create Date: 2025-10-14 18:03:01.692287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958d8a967fc0'
down_revision: Union[str, Sequence[str], None] = 'fbde3b86fceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('email', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'email')
    # ### end Alembic commands ###
