"""added video field in PublicInterviewAttempt table

Revision ID: e45094d53215
Revises: 8b69ef4c92ad
Create Date: 2025-10-14 20:31:34.385894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45094d53215'
down_revision: Union[str, Sequence[str], None] = '8b69ef4c92ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_interview_attempts', sa.Column('video', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_interview_attempts', 'video')
    # ### end Alembic commands ###
