"""changes in interview table

Revision ID: fbde3b86fceb
Revises: 085f4c565a6c
Create Date: 2025-10-13 22:17:14.965525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbde3b86fceb'
down_revision: Union[str, Sequence[str], None] = '085f4c565a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('interviews', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('interviews', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'feedback')
    op.drop_column('interviews', 'status')
    op.drop_column('interviews', 'score')
    # ### end Alembic commands ###
